In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/student_dataset.csv")

In [ ]:
df.shape

(500, 15)

In [ ]:
df["Department"].unique()

array(['ECE', 'ME', 'EEE', 'IT', 'CE', 'CSE', 'cse'], dtype=object)

In [ ]:
df["Department"].nunique()

7

In [ ]:
df["Department"].value_counts()

Department
EEE    104
CSE     85
CE      80
ME      78
IT      70
ECE     66
cse     17
Name: count, dtype: int64

In [ ]:
df["City"].value_counts()

City
Jalandhar     73
Delhi         72
Jaipur        70
Amritsar      64
Chandigarh    58
Pune          56
Mumbai        49
Ludhiana      48
Name: count, dtype: int64

In [ ]:
df["Gender"].value_counts()

Gender
Female    244
Male      225
male       21
FEMALE     10
Name: count, dtype: int64

In [ ]:
df["Placement_Status"].value_counts()

Placement_Status
Not Placed    325
Placed        165
placed         10
Name: count, dtype: int64

Univariate Analysis

Univariate = One Variable

In [ ]:
print(df["CGPA"].mean())
print(df["CGPA"].mode())
print(df["CGPA"].median())
print(df["CGPA"].max())
print(df["CGPA"].min())

7.6941041666666665
0    8.83
Name: CGPA, dtype: float64
7.67
15.0
5.5

Bivatiate Analysis

Relationship between TWO variables

In [ ]:
# groupby(): method in pandas splits a DataFrame into distinct groups based on one or more column values
# Departments vs Average CGPA
df.groupby("Department")["CGPA"].mean()

Department
CE     7.644750
CSE    7.683415
ECE    7.717846
EEE    7.583333
IT     7.693529
ME     7.809000
cse    8.084375
Name: CGPA, dtype: float64

In [ ]:
# Department VS Attendance
df.groupby("Department")["Attendance"].mean()

Department
CE     78.215190
CSE    81.604938
ECE    83.126984
EEE    82.121212
IT     81.867647
ME     78.266667
cse    82.928571
Name: Attendance, dtype: float64

In [ ]:
#Placement Vs CGPA
df.groupby("Placement_Status")["CGPA"].mean()

Placement_Status
Not Placed    7.226186
Placed        8.652658
placed        7.148000
Name: CGPA, dtype: float64

In [1]:
# Average Study Hours
df.groupby("Department")["Study_Hours"].mean()

NameError: name 'df' is not defined

Multivariate Analysis

Relationship among multiple variables

In [ ]:
df.groupby("Department")[["CGPA","Attendance"]].mean()

                CGPA  Attendance
Department
CE          7.644750   78.215190
CSE         7.683415   81.604938
ECE         7.717846   83.126984
EEE         7.583333   82.121212
IT          7.693529   81.867647
ME          7.809000   78.266667
cse         8.084375   82.928571

In [ ]:
# Crosstab: It provides a tabular summary that shows the frequency
#distribution or raw count of how often combinations of
# specific categories appear together in the dataset.
pd.crosstab(df["Department"],
            df["Placement_Status"])

Placement_Status  Not Placed  Placed  placed
Department
CE                        58      20       2
CSE                       53      30       2
ECE                       41      23       2
EEE                       74      29       1
IT                        44      25       1
ME                        48      28       2
cse                        7      10       0

In [ ]:
# It determines how strongly and in what direction two variables tend to change together.
# 1.0 (Perfect Positive Correlation): As one variable increases, the other increases proportionally.
# -1.0 (Perfect Negative Correlation): As one variable increases, the other decreases proportionally.
# 0.0 (No Linear Correlation): The movement of one variable does not predict the movement of the other.
corr = df.corr(numeric_only=True)

corr

,Student_ID,Age,Semester,CGPA,Attendance,Family_Income,Backlogs,Study_Hours
Student_ID,1.000000,-0.069646,-0.012505,-0.031509,-0.021553,0.050111,0.069109,-0.028765
Age,-0.069646,1.000000,-0.040528,0.026135,0.065172,0.021759,0.072956,-0.018136
Semester,-0.012505,-0.040528,1.000000,0.015458,-0.028209,0.035709,0.005086,0.009315
CGPA,-0.031509,0.026135,0.015458,1.000000,-0.082913,-0.076929,0.004689,-0.020506
Attendance,-0.021553,0.065172,-0.028209,-0.082913,1.000000,0.085139,0.029096,0.019234
Family_Income,0.050111,0.021759,0.035709,-0.076929,0.085139,1.000000,0.031026,-0.088420
Backlogs,0.069109,0.072956,0.005086,0.004689,0.029096,0.031026,1.000000,0.021178
Study_Hours,-0.028765,-0.018136,0.009315,-0.020506,0.019234,-0.088420,0.021178,1.000000

In [ ]:
# Highest CGPA
df.sort_values(by="CGPA",
ascending=False)

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship
337,1338,Muskan Joshi,Male,23.0,IT,4,15.0,85.0,Not Placed,Mumbai,Yes,1362978,1,4.3,No
16,1017,Deepak Mehta,Male,21.0,ECE,5,15.0,64.0,Not Placed,Pune,Yes,306091,4,6.9,Yes
55,1056,Komal Arora,Male,22.0,EEE,2,12.5,73.0,Not Placed,Amritsar,No,370262,1,2.7,Yes
406,1407,Simran Arora,Male,21.0,EEE,5,12.5,80.0,Not Placed,Jalandhar,No,472028,4,4.9,No
262,1263,Harsh Singh,Male,22.0,CSE,4,12.5,79.0,Not Placed,Jalandhar,No,989526,2,4.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,1358,Vikas Arora,Female,19.0,IT,1,NaN,94.0,Not Placed,Delhi,Yes,414483,2,2.9,No
409,1410,Aman Kaur,Female,20.0,ME,1,NaN,72.0,Not Placed,Mumbai,No,1204762,3,6.6,Yes
421,1422,Arjun Mehta,Female,18.0,CSE,8,NaN,90.0,Not Placed,Pune,Yes,791936,2,5.2,Yes
423,1424,Deepak Singh,Female,21.0,CSE,6,NaN,97.0,Not Placed,Jaipur,No,1389528,2,4.8,Yes
432,1433,Simran Arora,Female,23.0,CSE,3,NaN,93.0,Placed,Jalandhar,No,1284121,0,4.7,Yes

In [ ]:
# Lowest Attenance on top
df.sort_values(by="Attendance")

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship
301,1302,Arjun Patel,Female,19.0,CE,8,9.79,60.0,Not Placed,Ludhiana,No,1134631,1,7.3,Yes
271,1272,Deepak Verma,Female,NaN,IT,4,5.58,60.0,Not Placed,Amritsar,Yes,922153,2,1.9,No
242,1243,Anjali Arora,Male,21.0,IT,5,6.05,60.0,Not Placed,Jaipur,Yes,581853,4,3.2,Yes
483,1484,Sneha Kumar,Male,23.0,ME,6,7.16,60.0,Not Placed,Jalandhar,No,936844,2,7.8,Yes
238,1239,Neha Verma,Female,24.0,EEE,6,9.43,61.0,Not Placed,Mumbai,Yes,1380924,1,6.9,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,1426,Manpreet Kumar,Female,21.0,EEE,1,5.89,NaN,Not Placed,NaN,Yes,512929,3,4.7,No
459,1460,Harsh Mehta,Male,19.0,EEE,1,5.73,NaN,Not Placed,Jalandhar,Yes,1111572,2,3.3,No
466,1467,Komal Sharma,Female,18.0,CSE,8,8.65,NaN,Placed,Delhi,No,1313842,3,4.4,Yes
471,1472,Manpreet Sharma,Female,20.0,ECE,2,7.91,NaN,Not Placed,Chandigarh,No,700449,4,1.8,No
490,1354,Komal Kumar,male,20.0,cse,4,8.96,NaN,Placed,Jalandhar,No,1064454,2,2.1,Yes

In [ ]:
# Top 10 according to CGPA
df.nlargest(10,"CGPA")

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship
16,1017,Deepak Mehta,Male,21.0,ECE,5,15.00,64.0,Not Placed,Pune,Yes,306091,4,6.9,Yes
337,1338,Muskan Joshi,Male,23.0,IT,4,15.00,85.0,Not Placed,Mumbai,Yes,1362978,1,4.3,No
55,1056,Komal Arora,Male,22.0,EEE,2,12.50,73.0,Not Placed,Amritsar,No,370262,1,2.7,Yes
262,1263,Harsh Singh,Male,22.0,CSE,4,12.50,79.0,Not Placed,Jalandhar,No,989526,2,4.2,Yes
406,1407,Simran Arora,Male,21.0,EEE,5,12.50,80.0,Not Placed,Jalandhar,No,472028,4,4.9,No
301,1302,Arjun Patel,Female,19.0,CE,8,9.79,60.0,Not Placed,Ludhiana,No,1134631,1,7.3,Yes
388,1389,Sneha Patel,Female,23.0,IT,4,9.78,92.0,Placed,Jalandhar,Yes,740392,3,7.2,Yes
328,1329,Vikas Joshi,Female,22.0,IT,5,9.76,85.0,Placed,Amritsar,No,1357847,4,4.4,No
67,1068,Priya Patel,male,23.0,ME,7,9.75,69.0,Not Placed,Pune,Yes,464757,4,7.8,No
382,1383,Arjun Patel,Male,24.0,IT,3,9.75,99.0,Placed,Pune,Yes,1123718,0,7.5,Yes

In [ ]:
# Students with CGPA > 9
df[df["CGPA"]>9]

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship
9,1010,Simran Gupta,Female,19.0,ME,1,9.60,76.0,placed,Chandigarh,Yes,825884,4,5.3,Yes
16,1017,Deepak Mehta,Male,21.0,ECE,5,15.00,64.0,Not Placed,Pune,Yes,306091,4,6.9,Yes
17,1018,Anjali Singh,Female,21.0,ME,4,9.22,63.0,Not Placed,Chandigarh,No,204520,3,2.9,No
20,1021,Manpreet Kaur,Female,23.0,CE,6,9.52,73.0,Not Placed,Mumbai,Yes,757034,3,1.9,No
26,1027,Simran Patel,Female,22.0,EEE,3,9.48,75.0,Placed,Chandigarh,Yes,1064644,0,2.3,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,1483,Rohit Sharma,Male,22.0,ME,2,9.70,85.0,Placed,Amritsar,No,866386,4,5.2,Yes
488,1489,Harsh Kaur,Female,22.0,ME,7,9.23,100.0,Placed,Pune,Yes,982661,4,6.1,Yes
489,1490,Vikas Singh,Male,19.0,IT,8,9.28,68.0,Not Placed,Mumbai,Yes,310914,2,3.5,No
491,1108,Muskan Patel,Male,20.0,cse,3,9.59,81.0,Placed,Pune,Yes,675095,1,2.1,No
498,1035,Riya Mehta,Female,19.0,ECE,1,9.34,66.0,Not Placed,Jaipur,Yes,568861,4,4.3,Yes

In [ ]:
# Placed students
df[df["Placement_Status"]=="Placed"]

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship
0,1001,Simran Sharma,Female,19.0,ECE,3,8.67,94.0,Placed,Ludhiana,No,266653,0,1.7,Yes
6,1007,Komal Patel,Male,23.0,ME,7,NaN,89.0,Placed,Chandigarh,No,492826,1,6.2,No
8,1009,Manpreet Kaur,male,21.0,CE,8,7.78,95.0,Placed,Delhi,Yes,1326108,2,6.4,No
14,1015,Muskan Verma,FEMALE,55.0,ME,4,7.82,96.0,Placed,Pune,Yes,1191896,3,2.3,Yes
19,1020,Priya Joshi,Male,24.0,ECE,2,8.06,75.0,Placed,Jaipur,Yes,1394695,1,5.1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,1481,Pooja Mehta,Female,24.0,CE,3,8.94,88.0,Placed,Mumbai,Yes,1204496,0,2.0,Yes
482,1483,Rohit Sharma,Male,22.0,ME,2,9.70,85.0,Placed,Amritsar,No,866386,4,5.2,Yes
488,1489,Harsh Kaur,Female,22.0,ME,7,9.23,100.0,Placed,Pune,Yes,982661,4,6.1,Yes
490,1354,Komal Kumar,male,20.0,cse,4,8.96,NaN,Placed,Jalandhar,No,1064454,2,2.1,Yes
491,1108,Muskan Patel,Male,20.0,cse,3,9.59,81.0,Placed,Pune,Yes,675095,1,2.1,No

In [ ]:
df[df["Hostel"]=="Yes"]

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship
1,1002,Muskan Arora,Male,22.0,ECE,7,6.45,97.0,Not Placed,Jalandhar,Yes,534829,3,3.4,Yes
2,1003,Rohit Patel,Male,18.0,ME,2,7.04,82.0,Not Placed,Jalandhar,Yes,1163483,4,1.9,No
3,1004,Rahul Joshi,Female,24.0,EEE,6,7.98,64.0,Not Placed,Delhi,Yes,806890,0,7.0,Yes
4,1005,Riya Gupta,Female,23.0,IT,3,7.09,73.0,Not Placed,Jalandhar,Yes,1477440,1,4.7,Yes
5,1006,Neha Mehta,Female,20.0,EEE,4,8.44,150.0,Not Placed,Amritsar,Yes,861552,3,2.9,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,1166,Karan Gupta,Female,NaN,CE,8,6.54,74.0,Not Placed,Jalandhar,Yes,1171034,0,4.9,No
494,1325,Aman Verma,Female,24.0,ECE,2,6.26,99.0,Not Placed,Delhi,Yes,395433,3,5.6,Yes
496,1478,Priya Singh,Female,20.0,ME,3,8.16,70.0,Not Placed,Jalandhar,Yes,567755,1,2.1,Yes
498,1035,Riya Mehta,Female,19.0,ECE,1,9.34,66.0,Not Placed,Jaipur,Yes,568861,4,4.3,Yes
499,1324,Manpreet Singh,Male,22.0,EEE,5,6.22,81.0,Not Placed,Pune,Yes,681954,3,3.7,Yes

In [ ]:
df[df["City"]=="Delhi"]

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship
3,1004,Rahul Joshi,Female,24.0,EEE,6,7.98,64.0,Not Placed,Delhi,Yes,806890,0,7.0,Yes
7,1008,Komal Kumar,Female,20.0,ECE,3,7.69,65.0,Not Placed,Delhi,Yes,520531,1,6.5,No
8,1009,Manpreet Kaur,male,21.0,CE,8,7.78,95.0,Placed,Delhi,Yes,1326108,2,6.4,No
13,1014,Komal Joshi,Male,22.0,ECE,1,5.81,100.0,Not Placed,Delhi,Yes,341348,0,7.0,Yes
15,1016,Kunal Patel,Female,21.0,ME,1,8.40,66.0,Not Placed,Delhi,No,911569,0,2.7,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1476,Harsh Patel,Female,21.0,EEE,1,6.75,64.0,Not Placed,Delhi,Yes,1289723,2,3.9,No
478,1479,Priya Patel,Male,21.0,IT,6,6.29,95.0,Not Placed,Delhi,No,921099,1,3.6,Yes
481,1482,Pooja Sharma,Female,22.0,ECE,8,7.04,80.0,Not Placed,Delhi,Yes,1423544,4,2.6,No
494,1325,Aman Verma,Female,24.0,ECE,2,6.26,99.0,Not Placed,Delhi,Yes,395433,3,5.6,Yes
497,1174,Aman Verma,Female,20.0,CSE,8,8.33,61.0,Not Placed,Delhi,No,224853,0,4.7,No

In [ ]:
# Feature Engineering
#  Generating entirely new variables from existing data. For example, extracting "Day of the Week" and "Is Holiday" columns from raw date
df["Excellent"]=df["CGPA"]>=9

df.head()

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship,Excellent
0,1001,Simran Sharma,Female,19.0,ECE,3,8.67,94.0,Placed,Ludhiana,No,266653,0,1.7,Yes,False
1,1002,Muskan Arora,Male,22.0,ECE,7,6.45,97.0,Not Placed,Jalandhar,Yes,534829,3,3.4,Yes,False
2,1003,Rohit Patel,Male,18.0,ME,2,7.04,82.0,Not Placed,Jalandhar,Yes,1163483,4,1.9,No,False
3,1004,Rahul Joshi,Female,24.0,EEE,6,7.98,64.0,Not Placed,Delhi,Yes,806890,0,7.0,Yes,False
4,1005,Riya Gupta,Female,23.0,IT,3,7.09,73.0,Not Placed,Jalandhar,Yes,1477440,1,4.7,Yes,False

In [ ]:
df["Scholarship"]=(
    (df["CGPA"]>=8.5)&
    (df["Attendance"]>=90)
)

df.head()

,Student_ID,Name,Gender,Age,Department,Semester,CGPA,Attendance,Placement_Status,City,Hostel,Family_Income,Backlogs,Study_Hours,Internship,Excellent,Scholarship
0,1001,Simran Sharma,Female,19.0,ECE,3,8.67,94.0,Placed,Ludhiana,No,266653,0,1.7,Yes,False,True
1,1002,Muskan Arora,Male,22.0,ECE,7,6.45,97.0,Not Placed,Jalandhar,Yes,534829,3,3.4,Yes,False,False
2,1003,Rohit Patel,Male,18.0,ME,2,7.04,82.0,Not Placed,Jalandhar,Yes,1163483,4,1.9,No,False,False
3,1004,Rahul Joshi,Female,24.0,EEE,6,7.98,64.0,Not Placed,Delhi,Yes,806890,0,7.0,Yes,False,False
4,1005,Riya Gupta,Female,23.0,IT,3,7.09,73.0,Not Placed,Jalandhar,Yes,1477440,1,4.7,Yes,False,False